name: CI Workflow

on:
  push:
    branches: 
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout código
      uses: actions/checkout@v3
    
    - name: extraer el SHA del commit
      id: sha
      run: echo "COMMIT_SHA=${GITHUB_SHA::6}" >> $GITHUB_OUTPUT

    - name: Log in GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Construir y publicar imagen
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/test-image:${{ steps.sha.outputs.COMMIT_SHA }}

    - name: Verificar la imagen publicada
      run: |
        docker pull ghcr.io/${{ github.repository_owner }}/test-image:${{ steps.sha.outputs.COMMIT_SHA }}
        docker run --rm ghcr.io/${{ github.repository_owner }}/test-image:${{ steps.sha.outputs.COMMIT_SHA }}